apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ include "crud-chart.fullname" . }}-monitor"
  labels:
    {{- include "crud-chart.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: http
      scheme: http
      path: /metrics
      interval: 5s
  selector:
    matchLabels:
      {{- include "crud-chart.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - "{{ $.Release.Namespace }}"