version: '3'
services:
  app:
    container_name: app
    image: antonnv22/crud:0.0.61
    networks:
      - crud-network
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_PASSWORD: postgres
  db:
    container_name: db
    image: postgres:14.4
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - crud-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      TZ: 'Europe/Moscow'

networks:
  crud-network: